In [1]:
#Utilizando os melhores parametros definido no exercício anterior e refazendo o modelo com todos os dados.

import pandas as pd
import numpy as np
import seaborn as sns
import torch.nn as nn
import torch
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
torch.__version__

'1.9.1+cpu'

In [2]:
np.random.seed(123)
torch.manual_seed(123)

In [3]:
previsores = pd.read_csv('entradas_breast.csv')
classe = pd.read_csv('saidas_breast.csv')

In [4]:
previsores = torch.tensor(np.array(previsores), dtype=torch.float)
classe = torch.tensor(np.array(classe), dtype=torch.float)

In [5]:
type(previsores)

torch.Tensor

In [6]:
train_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(previsores, classe), batch_size=10, shuffle=True)

In [7]:
class classificador_torch(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense0 = nn.Linear(30, 8)
        torch.nn.init.normal_(self.dense0.weight, mean=0.0, std=0.05)
        self.dense1 = nn.Linear(8, 8)
        torch.nn.init.normal_(self.dense0.weight, mean=0.0, std=0.05)
        self.dense2 = nn.Linear(8,1)
        self.activation = nn.ReLU()
        self.dropout = nn.Dropout(0.2)
        self.output = nn.Sigmoid()
        
    def forward(self, X):
        X = self.dense0(X)
        X = self.activation(X)
        X = self.dropout(X)
        X = self.dense1(X)
        X = self.activation(X)
        X = self.dropout(X)
        X = self.dense2(X)
        X = self.output(X)
        return X

In [8]:
classificador = classificador_torch()

In [11]:
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(classificador.parameters(), lr=0.001, weight_decay=0.0001)

In [14]:
#Treinamento do modelo

for epoch in range(100):
    running_loss = 0.
    for data in train_loader:
        inputs, labels = data
        optimizer.zero_grad()
        
        outputs = classificador(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        print('Época %3d: perda %.5f'%(epoch+1, running_loss/len(train_loader)))

Época   1: perda 0.00588
Época   1: perda 0.01050
Época   1: perda 0.01584
Época   1: perda 0.02688
Época   1: perda 0.02805
Época   1: perda 0.03717
Época   1: perda 0.04338
Época   1: perda 0.04615
Época   1: perda 0.04823
Época   1: perda 0.05351
Época   1: perda 0.05512
Época   1: perda 0.05640
Época   1: perda 0.05936
Época   1: perda 0.06626
Época   1: perda 0.06781
Época   1: perda 0.07312
Época   1: perda 0.07784
Época   1: perda 0.08314
Época   1: perda 0.09030
Época   1: perda 0.09490
Época   1: perda 0.09636
Época   1: perda 0.10161
Época   1: perda 0.10467
Época   1: perda 0.10725
Época   1: perda 0.10956
Época   1: perda 0.11492
Época   1: perda 0.11596
Época   1: perda 0.11816
Época   1: perda 0.12407
Época   1: perda 0.12558
Época   1: perda 0.12720
Época   1: perda 0.13397
Época   1: perda 0.14082
Época   1: perda 0.14156
Época   1: perda 0.15232
Época   1: perda 0.16036
Época   1: perda 0.16428
Época   1: perda 0.16616
Época   1: perda 0.16764
Época   1: perda 0.17294


Época   7: perda 0.09900
Época   7: perda 0.10473
Época   7: perda 0.11249
Época   7: perda 0.11888
Época   7: perda 0.11970
Época   7: perda 0.12638
Época   7: perda 0.13345
Época   7: perda 0.14218
Época   7: perda 0.15179
Época   7: perda 0.15344
Época   7: perda 0.15696
Época   7: perda 0.15908
Época   7: perda 0.16694
Época   7: perda 0.17411
Época   7: perda 0.18334
Época   7: perda 0.19073
Época   7: perda 0.19364
Época   7: perda 0.19765
Época   7: perda 0.20166
Época   7: perda 0.20610
Época   7: perda 0.21280
Época   7: perda 0.21866
Época   7: perda 0.22509
Época   7: perda 0.22558
Época   7: perda 0.23117
Época   7: perda 0.23172
Época   7: perda 0.23834
Época   7: perda 0.24321
Época   7: perda 0.24429
Época   7: perda 0.24950
Época   7: perda 0.25347
Época   7: perda 0.25463
Época   7: perda 0.26048
Época   8: perda 0.00213
Época   8: perda 0.00773
Época   8: perda 0.01202
Época   8: perda 0.01731
Época   8: perda 0.02853
Época   8: perda 0.03377
Época   8: perda 0.03585


Época  13: perda 0.22549
Época  13: perda 0.22987
Época  13: perda 0.23095
Época  13: perda 0.23572
Época  13: perda 0.23890
Época  14: perda 0.00218
Época  14: perda 0.00435
Época  14: perda 0.00921
Época  14: perda 0.01182
Época  14: perda 0.01359
Época  14: perda 0.01938
Época  14: perda 0.02129
Época  14: perda 0.02526
Época  14: perda 0.03002
Época  14: perda 0.03190
Época  14: perda 0.03253
Época  14: perda 0.04308
Época  14: perda 0.05278
Época  14: perda 0.05479
Época  14: perda 0.05675
Época  14: perda 0.06175
Época  14: perda 0.06891
Época  14: perda 0.07054
Época  14: perda 0.07608
Época  14: perda 0.07772
Época  14: perda 0.08036
Época  14: perda 0.08454
Época  14: perda 0.08522
Época  14: perda 0.08716
Época  14: perda 0.08913
Época  14: perda 0.09473
Época  14: perda 0.10211
Época  14: perda 0.10846
Época  14: perda 0.10947
Época  14: perda 0.11005
Época  14: perda 0.11546
Época  14: perda 0.12318
Época  14: perda 0.12718
Época  14: perda 0.14286
Época  14: perda 0.14389


Época  20: perda 0.07984
Época  20: perda 0.08562
Época  20: perda 0.08921
Época  20: perda 0.09075
Época  20: perda 0.09181
Época  20: perda 0.09668
Época  20: perda 0.09842
Época  20: perda 0.10322
Época  20: perda 0.10688
Época  20: perda 0.10796
Época  20: perda 0.11397
Época  20: perda 0.11596
Época  20: perda 0.12646
Época  20: perda 0.13251
Época  20: perda 0.14112
Época  20: perda 0.14919
Época  20: perda 0.15681
Época  20: perda 0.16530
Época  20: perda 0.16838
Época  20: perda 0.17326
Época  20: perda 0.17488
Época  20: perda 0.18116
Época  20: perda 0.19160
Época  20: perda 0.19282
Época  20: perda 0.20294
Época  20: perda 0.20519
Época  20: perda 0.20647
Época  20: perda 0.20848
Época  20: perda 0.21212
Época  20: perda 0.21308
Época  20: perda 0.21811
Época  20: perda 0.22273
Época  20: perda 0.22411
Época  20: perda 0.23433
Época  20: perda 0.23756
Época  20: perda 0.25340
Época  20: perda 0.25496
Época  20: perda 0.25735
Época  20: perda 0.26194
Época  20: perda 0.26250


Época  26: perda 0.16454
Época  26: perda 0.16786
Época  26: perda 0.17471
Época  26: perda 0.17815
Época  26: perda 0.18047
Época  26: perda 0.18153
Época  26: perda 0.18370
Época  26: perda 0.19194
Época  26: perda 0.19749
Época  26: perda 0.19922
Época  26: perda 0.20368
Época  26: perda 0.20805
Época  26: perda 0.21160
Época  26: perda 0.21655
Época  26: perda 0.21744
Época  26: perda 0.22002
Época  26: perda 0.22345
Época  26: perda 0.22510
Época  26: perda 0.22590
Época  26: perda 0.23291
Época  26: perda 0.23395
Época  27: perda 0.00140
Época  27: perda 0.00218
Época  27: perda 0.00526
Época  27: perda 0.01246
Época  27: perda 0.01814
Época  27: perda 0.02032
Época  27: perda 0.02280
Época  27: perda 0.03028
Época  27: perda 0.03570
Época  27: perda 0.04226
Época  27: perda 0.04443
Época  27: perda 0.04574
Época  27: perda 0.04762
Época  27: perda 0.06046
Época  27: perda 0.06589
Época  27: perda 0.07104
Época  27: perda 0.07254
Época  27: perda 0.07894
Época  27: perda 0.08003


Época  32: perda 0.18214
Época  32: perda 0.18334
Época  32: perda 0.18570
Época  32: perda 0.19470
Época  32: perda 0.20438
Época  32: perda 0.21002
Época  32: perda 0.21582
Época  32: perda 0.22180
Época  32: perda 0.22678
Época  32: perda 0.23277
Época  32: perda 0.23803
Época  32: perda 0.24848
Época  32: perda 0.25493
Época  32: perda 0.25733
Época  32: perda 0.26438
Época  33: perda 0.00412
Época  33: perda 0.00759
Época  33: perda 0.01280
Época  33: perda 0.02137
Época  33: perda 0.02791
Época  33: perda 0.03644
Época  33: perda 0.04493
Época  33: perda 0.05017
Época  33: perda 0.05330
Época  33: perda 0.05407
Época  33: perda 0.05625
Época  33: perda 0.05821
Época  33: perda 0.06303
Época  33: perda 0.06535
Época  33: perda 0.06699
Época  33: perda 0.06801
Época  33: perda 0.07300
Época  33: perda 0.07522
Época  33: perda 0.07757
Época  33: perda 0.08292
Época  33: perda 0.08807
Época  33: perda 0.09943
Época  33: perda 0.10092
Época  33: perda 0.10495
Época  33: perda 0.10837


Época  39: perda 0.03457
Época  39: perda 0.03543
Época  39: perda 0.04461
Época  39: perda 0.04709
Época  39: perda 0.04888
Época  39: perda 0.05522
Época  39: perda 0.06773
Época  39: perda 0.06962
Época  39: perda 0.07123
Época  39: perda 0.07830
Época  39: perda 0.08408
Época  39: perda 0.08858
Época  39: perda 0.09031
Época  39: perda 0.09633
Época  39: perda 0.09752
Época  39: perda 0.09885
Época  39: perda 0.09989
Época  39: perda 0.10208
Época  39: perda 0.10291
Época  39: perda 0.10499
Época  39: perda 0.11048
Época  39: perda 0.11861
Época  39: perda 0.12097
Época  39: perda 0.12629
Época  39: perda 0.12765
Época  39: perda 0.13344
Época  39: perda 0.13510
Época  39: perda 0.14038
Época  39: perda 0.14862
Época  39: perda 0.15335
Época  39: perda 0.15777
Época  39: perda 0.16122
Época  39: perda 0.16953
Época  39: perda 0.17054
Época  39: perda 0.17362
Época  39: perda 0.17895
Época  39: perda 0.18522
Época  39: perda 0.18927
Época  39: perda 0.19308
Época  39: perda 0.19350


Época  45: perda 0.13677
Época  45: perda 0.14086
Época  45: perda 0.14260
Época  45: perda 0.14679
Época  45: perda 0.15141
Época  45: perda 0.15421
Época  45: perda 0.16001
Época  45: perda 0.16576
Época  45: perda 0.16741
Época  45: perda 0.17639
Época  45: perda 0.18608
Época  45: perda 0.18834
Época  45: perda 0.18979
Época  45: perda 0.19058
Época  45: perda 0.19449
Época  45: perda 0.20385
Época  45: perda 0.20959
Época  45: perda 0.21311
Época  45: perda 0.22010
Época  45: perda 0.22155
Época  45: perda 0.22341
Época  45: perda 0.23196
Época  45: perda 0.23507
Época  46: perda 0.00066
Época  46: perda 0.00169
Época  46: perda 0.00795
Época  46: perda 0.00831
Época  46: perda 0.00925
Época  46: perda 0.01395
Época  46: perda 0.02872
Época  46: perda 0.03513
Época  46: perda 0.03998
Época  46: perda 0.04149
Época  46: perda 0.04752
Época  46: perda 0.05260
Época  46: perda 0.06149
Época  46: perda 0.06706
Época  46: perda 0.06894
Época  46: perda 0.07031
Época  46: perda 0.07477


Época  51: perda 0.20969
Época  51: perda 0.21297
Época  51: perda 0.21940
Época  51: perda 0.22295
Época  51: perda 0.22737
Época  51: perda 0.23127
Época  51: perda 0.23324
Época  52: perda 0.00132
Época  52: perda 0.00276
Época  52: perda 0.00690
Época  52: perda 0.00776
Época  52: perda 0.01589
Época  52: perda 0.02141
Época  52: perda 0.02361
Época  52: perda 0.02868
Época  52: perda 0.03831
Época  52: perda 0.03902
Época  52: perda 0.04049
Época  52: perda 0.04105
Época  52: perda 0.04217
Época  52: perda 0.06049
Época  52: perda 0.06974
Época  52: perda 0.07265
Época  52: perda 0.07365
Época  52: perda 0.07498
Época  52: perda 0.07581
Época  52: perda 0.08323
Época  52: perda 0.08502
Época  52: perda 0.08586
Época  52: perda 0.08648
Época  52: perda 0.08844
Época  52: perda 0.09442
Época  52: perda 0.10075
Época  52: perda 0.10169
Época  52: perda 0.11037
Época  52: perda 0.11146
Época  52: perda 0.11294
Época  52: perda 0.11548
Época  52: perda 0.12337
Época  52: perda 0.12822


Época  58: perda 0.06926
Época  58: perda 0.07045
Época  58: perda 0.07275
Época  58: perda 0.07534
Época  58: perda 0.08424
Época  58: perda 0.08738
Época  58: perda 0.09434
Época  58: perda 0.09963
Época  58: perda 0.10065
Época  58: perda 0.10841
Época  58: perda 0.11034
Época  58: perda 0.11714
Época  58: perda 0.12646
Época  58: perda 0.12828
Época  58: perda 0.13026
Época  58: perda 0.13416
Época  58: perda 0.14026
Época  58: perda 0.14354
Época  58: perda 0.15951
Época  58: perda 0.16392
Época  58: perda 0.17466
Época  58: perda 0.17871
Época  58: perda 0.18253
Época  58: perda 0.19366
Época  58: perda 0.19576
Época  58: perda 0.20269
Época  58: perda 0.20870
Época  58: perda 0.21674
Época  58: perda 0.22674
Época  58: perda 0.22830
Época  58: perda 0.23204
Época  58: perda 0.23308
Época  58: perda 0.23553
Época  58: perda 0.23788
Época  58: perda 0.24077
Época  58: perda 0.24318
Época  58: perda 0.24333
Época  58: perda 0.24515
Época  58: perda 0.25168
Época  58: perda 0.25373


Época  66: perda 0.18034
Época  66: perda 0.18502
Época  66: perda 0.19338
Época  66: perda 0.19777
Época  66: perda 0.20743
Época  66: perda 0.21756
Época  66: perda 0.21890
Época  66: perda 0.21969
Época  66: perda 0.22531
Época  66: perda 0.22813
Época  66: perda 0.23413
Época  66: perda 0.23943
Época  66: perda 0.24171
Época  66: perda 0.24645
Época  66: perda 0.25151
Época  66: perda 0.25414
Época  66: perda 0.25884
Época  66: perda 0.26695
Época  66: perda 0.27020
Época  66: perda 0.28003
Época  66: perda 0.29081
Época  67: perda 0.00152
Época  67: perda 0.00485
Época  67: perda 0.00955
Época  67: perda 0.01545
Época  67: perda 0.02346
Época  67: perda 0.02610
Época  67: perda 0.02720
Época  67: perda 0.02828
Época  67: perda 0.03856
Época  67: perda 0.04164
Época  67: perda 0.04771
Época  67: perda 0.05087
Época  67: perda 0.05824
Época  67: perda 0.05929
Época  67: perda 0.06045
Época  67: perda 0.07076
Época  67: perda 0.07255
Época  67: perda 0.07380
Época  67: perda 0.07582


Época  72: perda 0.22825
Época  72: perda 0.23268
Época  72: perda 0.24255
Época  72: perda 0.25001
Época  72: perda 0.25274
Época  72: perda 0.25678
Época  72: perda 0.25888
Época  72: perda 0.26277
Época  72: perda 0.26999
Época  72: perda 0.27437
Época  73: perda 0.00556
Época  73: perda 0.01232
Época  73: perda 0.02026
Época  73: perda 0.02661
Época  73: perda 0.02825
Época  73: perda 0.02985
Época  73: perda 0.03545
Época  73: perda 0.04160
Época  73: perda 0.04658
Época  73: perda 0.05205
Época  73: perda 0.05942
Época  73: perda 0.06007
Época  73: perda 0.06111
Época  73: perda 0.06189
Época  73: perda 0.06441
Época  73: perda 0.06627
Época  73: perda 0.06729
Época  73: perda 0.06886
Época  73: perda 0.07238
Época  73: perda 0.07359
Época  73: perda 0.07582
Época  73: perda 0.08009
Época  73: perda 0.08877
Época  73: perda 0.09190
Época  73: perda 0.09840
Época  73: perda 0.10864
Época  73: perda 0.11054
Época  73: perda 0.11102
Época  73: perda 0.12190
Época  73: perda 0.12615


Época  79: perda 0.04273
Época  79: perda 0.04485
Época  79: perda 0.04615
Época  79: perda 0.04679
Época  79: perda 0.04790
Época  79: perda 0.05030
Época  79: perda 0.05250
Época  79: perda 0.05551
Época  79: perda 0.05908
Época  79: perda 0.06083
Época  79: perda 0.06273
Época  79: perda 0.06667
Época  79: perda 0.07717
Época  79: perda 0.07929
Época  79: perda 0.08182
Época  79: perda 0.08345
Época  79: perda 0.08457
Época  79: perda 0.08570
Época  79: perda 0.08691
Época  79: perda 0.09177
Época  79: perda 0.09795
Época  79: perda 0.10154
Época  79: perda 0.10335
Época  79: perda 0.10559
Época  79: perda 0.10795
Época  79: perda 0.11081
Época  79: perda 0.11327
Época  79: perda 0.12084
Época  79: perda 0.12288
Época  79: perda 0.12794
Época  79: perda 0.13061
Época  79: perda 0.13417
Época  79: perda 0.13678
Época  79: perda 0.14208
Época  79: perda 0.14942
Época  79: perda 0.15103
Época  79: perda 0.15846
Época  79: perda 0.16792
Época  79: perda 0.18319
Época  79: perda 0.18864


Época  85: perda 0.14226
Época  85: perda 0.15237
Época  85: perda 0.15366
Época  85: perda 0.15506
Época  85: perda 0.16175
Época  85: perda 0.16659
Época  85: perda 0.16827
Época  85: perda 0.17287
Época  85: perda 0.17873
Época  85: perda 0.18653
Época  85: perda 0.18917
Época  85: perda 0.19203
Época  85: perda 0.19491
Época  85: perda 0.19706
Época  85: perda 0.19805
Época  85: perda 0.20242
Época  85: perda 0.20634
Época  85: perda 0.20915
Época  85: perda 0.21040
Época  85: perda 0.21486
Época  85: perda 0.21939
Época  85: perda 0.23518
Época  85: perda 0.23638
Época  85: perda 0.23965
Época  86: perda 0.00056
Época  86: perda 0.00576
Época  86: perda 0.01210
Época  86: perda 0.01396
Época  86: perda 0.01915
Época  86: perda 0.03723
Época  86: perda 0.04195
Época  86: perda 0.04356
Época  86: perda 0.05112
Época  86: perda 0.05819
Época  86: perda 0.05949
Época  86: perda 0.06085
Época  86: perda 0.06202
Época  86: perda 0.06417
Época  86: perda 0.06611
Época  86: perda 0.07070


Época  91: perda 0.14574
Época  91: perda 0.16087
Época  91: perda 0.16134
Época  91: perda 0.16458
Época  91: perda 0.16586
Época  91: perda 0.16713
Época  91: perda 0.17699
Época  91: perda 0.17766
Época  91: perda 0.17923
Época  91: perda 0.18465
Época  91: perda 0.18628
Época  91: perda 0.19583
Época  91: perda 0.20015
Época  91: perda 0.20224
Época  91: perda 0.20429
Época  91: perda 0.20964
Época  91: perda 0.21109
Época  91: perda 0.21585
Época  91: perda 0.21902
Época  91: perda 0.22385
Época  91: perda 0.22540
Época  91: perda 0.22938
Época  91: perda 0.24479
Época  91: perda 0.24588
Época  91: perda 0.24836
Época  92: perda 0.00688
Época  92: perda 0.00815
Época  92: perda 0.01944
Época  92: perda 0.02298
Época  92: perda 0.02687
Época  92: perda 0.02918
Época  92: perda 0.03392
Época  92: perda 0.03761
Época  92: perda 0.03965
Época  92: perda 0.05158
Época  92: perda 0.05748
Época  92: perda 0.06043
Época  92: perda 0.06130
Época  92: perda 0.06277
Época  92: perda 0.07091


Época  97: perda 0.09551
Época  97: perda 0.10004
Época  97: perda 0.10068
Época  97: perda 0.10236
Época  97: perda 0.10480
Época  97: perda 0.10769
Época  97: perda 0.11344
Época  97: perda 0.11678
Época  97: perda 0.11842
Época  97: perda 0.12147
Época  97: perda 0.13038
Época  97: perda 0.13135
Época  97: perda 0.13735
Época  97: perda 0.13990
Época  97: perda 0.14541
Época  97: perda 0.14662
Época  97: perda 0.15618
Época  97: perda 0.15814
Época  97: perda 0.16609
Época  97: perda 0.17253
Época  97: perda 0.17354
Época  97: perda 0.17964
Época  97: perda 0.18130
Época  97: perda 0.19135
Época  97: perda 0.20122
Época  97: perda 0.20407
Época  97: perda 0.21036
Época  97: perda 0.21097
Época  97: perda 0.21234
Época  97: perda 0.21519
Época  97: perda 0.21768
Época  97: perda 0.22028
Época  97: perda 0.22799
Época  97: perda 0.23470
Época  97: perda 0.23613
Época  97: perda 0.24187
Época  97: perda 0.24746
Época  97: perda 0.24867
Época  97: perda 0.25410
Época  98: perda 0.00171


In [15]:
novo = torch.tensor([[15.80,8.34,118,900,0.10,0.26,0.08,0.134,0.178,0.20,0.05,1098,0.87,4500,145.2,0.005,0.04,0.05,0.015,0.03,0.007,23.15,16.64,178.5,2018,0.14,0.185,0.84,158,0.363]], dtype = torch.float)

In [16]:
classificador.eval()

classificador_torch(
  (dense0): Linear(in_features=30, out_features=8, bias=True)
  (dense1): Linear(in_features=8, out_features=8, bias=True)
  (dense2): Linear(in_features=8, out_features=1, bias=True)
  (activation): ReLU()
  (dropout): Dropout(p=0.2, inplace=False)
  (output): Sigmoid()
)

In [17]:
previsao = classificador(novo)

In [18]:
previsao

tensor([[1.]], grad_fn=<SigmoidBackward>)

In [19]:
previsao = previsao.detach()
previsao

tensor([[1.]])

In [20]:
previsao = previsao.numpy()

In [21]:
type(previsao)

numpy.ndarray

In [22]:
previsao

array([[1.]], dtype=float32)

In [23]:
previsao = (previsao > 0.5)
previsao

array([[ True]])

In [24]:
#salvando o classificador:
classificador.state_dict()

OrderedDict([('dense0.weight',
              tensor([[-1.4990e-02,  6.7083e-03,  1.2485e-02,  6.1057e-03, -1.3822e-02,
                       -1.4067e-06,  1.1053e-02, -5.4433e-06, -7.0263e-04, -8.4592e-29,
                       -3.3932e-02, -2.9084e-02, -1.2062e-02, -5.9148e-03,  1.9563e-39,
                        6.2078e-39,  1.4643e-39, -4.6491e-39,  3.9069e-05, -6.6964e-39,
                       -5.9275e-03, -3.3482e-02, -3.8047e-02, -2.7868e-02,  7.0661e-02,
                       -9.0366e-04, -1.1764e-02, -1.1567e-02,  1.3315e-02, -9.2528e-07],
                      [-6.5833e-01,  1.0348e-01, -4.9525e-01, -1.1686e-01,  1.2365e-01,
                       -1.2294e-01,  5.5291e-02, -1.4157e-02,  2.7280e-02,  1.8405e-01,
                        6.9750e-03,  3.3230e-03,  1.6325e-04, -1.0280e-02,  3.0929e-02,
                        1.3038e-01, -5.5071e-01, -3.7309e-02,  9.9297e-02,  5.0691e-01,
                       -4.4191e-01,  2.0291e-01, -3.2636e-01,  2.0659e-01,  3.8398e-02,


In [25]:
torch.save(classificador.state_dict, 'classificador.pth')